# Generated by Django 4.2 on 2023-05-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyflow', '0002_moneyinformation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyinformation',
            name='pay_date',
            field=models.DateField(default='01-01-2000'),
        ),
        migrations.CreateModel(
            name='Cut_Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
