# Generated by Django 4.2 on 2023-05-15 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyflow', '0005_alter_moneyinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyinformation',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 13, 38, 32, 832572)),
        ),
    ]
