# Generated by Django 4.2 on 2023-05-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyflow', '0007_alter_moneyinformation_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyinformation',
            name='pay_date',
        ),
    ]
