# Generated by Django 4.2 on 2023-05-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyflow', '0009_alter_moneyinformation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cut_Off',
        ),
    ]
